project:
  type: website
  output-dir: docs

website:
  title: "Joon's blog"
  favicon: quarto_favicon.svg
  google-analytics: "G-LETXD56KZ0"
  navbar:
    title: 🧐
    right:
      - text: About
        href: about/index.qmd
      - text: Posts
        href: post/
      - cv.qmd
      - icon: github
        href: https://github.com/kimsjune
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css

editor: visual

