project:
  type: website
  output-dir: docs

website:
  title: "Joon's blog"
  favicon: quarto_favicon.svg
  google-analytics: "G-LETXD56KZ0"
  open-graph: true
  back-to-top-navigation: true
  page-footer: "Built with [Quarto](https://quarto.org/). License: [CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/)."
  navbar:
    title: "🧐 Joon's bioinformatics blog"
    right:
      - text: About
        href: about/index.qmd
      - text: Posts
        href: /
      - text: RNA-seq workshop
        href: https://kimsjune.github.io/ccir-rnaseq
      # - text: CV
      #   href: cv/index.qmd
      - icon: github
        href: https://github.com/kimsjune
      - icon: envelope
        href: mailto:seung.kim@lhsc.on.ca
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    email-obfuscation: javascript
    theme: 
      light: flatly
      dark: darkly
    css: styles.css

editor: visual

