---
title: "CV"
format:
  html: 
    toc: true
---

### Education

**PhD Biochemistry** <br> *Western University* [*2016-2022*]{.cvdate}

**BSc Hon. Specialization in Biochemistry of Infection and Immunity** <br> *Western University* [*2012-2016*]{.cvdate}

### Bioinformatics competencies

command line (proficient):

  - tools: `bowtie2`, `bwa`, `STAR`, `salmon`, `kallisto`, `fastqc`, `fastp`, `featureCounts`, `htseq-count`, `deeptools`
  - workflow: `snakemake`, `nextflow`
  - HPC: `linux`, `slurm`, `globus`
  
R (proficient): 

  - differential gene expression analysis: `edgeR`, `DESeq2`, `limma`, `voom`, `standR`
  - data wrangling and visualization: `ggplot2`, `ComplexHeatmap`, `tidyverse`
  - interactivity: `shiny`
              
python (beginner):

  - `numpy`, `pandas`, `matplotlib`, `scanpy`, `squidpy`


### Peer reviewed publications

**Kim, S. J.**, Cecchini, M.J., Woo, E., Jayawardena, N., Passos, D. T., Dick, F. A. & Mura, M. Spatially resolved gene expression profiles in fibrosing interstitial lung diseases. *Thorax* (*under review*) (2024).

**Kim, S. J.**, Kiser, P. K., Asfaha, S., DeKoter, R. P. & Dick, F. A. EZH2 inhibition stimulates repetitive element expression and viral mimicry in resting splenic B cells. *The EMBO Journal* 42, e114462 (2023).

**Kim, S. J.**, MacDonald, J. I. & Dick, F. A. Phosphorylation of the RB C-terminus regulates condensin II release from chromatin. *Journal of Biological Chemistry* 296, (2021).

**Kim, S. J.**, Asfaha, S. & Dick, F. A. CDK4 inhibitors thwart immunity by inhibiting phospho-RB-NF-κB complexes. *Mol Cell* 73, 1–2 (2019).

Ishak, C. A. et al. An RB-EZH2 complex mediates silencing of repetitive DNA sequences. *Mol Cell* 64, 1074–1087 (2016).

### Presentations

**Kim, S. J.**, Kiser, P. K., DeKoter, R. P. & Dick, F. A. Elucidating the mechanism behind EZH2 inhibition and immune activation. Oncology Research & Education Day. <br> London ON, Canada [2023]{.cvdate}

**Kim, S. J.**, Kiser, P. K., DeKoter, R. P. & Dick, F. A. Elucidating the mechanism behind EZH2 inhibition and immune activation. Oncology Research & Education Day. <br> London ON, Canada	[2022]{.cvdate}

**Kim, S. J.** & Dick, F.A. Elucidating the mechanism behind EZH2 inhibition and anti-viral immune signaling. Oncology Research & Education Day. <br> London ON, Canada			    [2021]{.cvdate}

**Kim, S. J.**, Ishak, C.A. & Dick, F.A. Pharmacological inhibition of EZH2 activates anti-viral immunity. London Immuno-Oncology Symposium
<br> London ON, Canada [2020]{.cvdate}

**Kim, S. J.**, Ishak, C.A. & Dick, F.A. Pharmacological inhibition of E1A-insensitive pRB-E2F1-EZH2 complex activates anti-viral immunity. ICGEB DNA Tumour Virus Meeting. <br> Trieste, Italy.	[2019]{.cvdate}

### Awards

Dr. William Zaharia Award [2024]{.cvdate}

Ontario Graduate Scholarship [2020]{.cvdate}

Howard Hughes Medical Institute Stipend [2018]{.cvdate}

Cancer Research and Technology Transfer Scholarship [2017]{.cvdate}

### Academic experiences
Advanced Sequencing Technologies and Applications. <br> Cold Spring Harbor Laboratory [2018]{.cvdate}

:::{.column-margin}
Source for CV style and guide:

Huang, Cynthia. 2023. “Publishing HTML and PDF Versions of a Quarto CV Without LaTex.” August 22, 2023. https://www.cynthiahqy.com/posts/cv-html-pdf. 
:::
